nome = input('Qual é o seu nome? ')
idade = input('Quantos anos você tem? ')
peso = input('Quantos quilos você pesa? ')
dia = input('Em que dia você nasceu? ')
mes = input('Em que mês você nasceu? ')
ano = input('Em que ano você nasceu? ')
nasceu = input('Onde você nasceu? ')
estadon = input('Em qual estado você nasceu? ')
paisn = input ('Em qual país você nasceu? ')    
morar = input('Em qual cidade você mora? ')
estado = input('Em qual estado você mora? ')
pais = input ('Em qual país você mora? ')             
print('Olá',nome,'Prazer em te conhecer :)')
print('você nasceu no dia',dia,'de',mes,'de',ano,'no município de',nasceu,'no estado do',estadon,'no',paisn,'sua idade e peso atual são respectivamentes',idade,'anos',peso,'quilos','atualmente você mora em',morar,estado,pais)
print('Cadastro finalizado, agora você pode fechar esta janela :3')

    # Tudo Certo!